### ISSUE TITLE
C Code Style

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/workflow_guidelines#3]
Do we want to select a C style guide?

[https://www.gnu.org/prep/standards/html_node/Writing-C.html](https://www.gnu.org/prep/standards/html_node/Writing-C.html)
[http://www.maultech.com/chrislott/resources/cstyle/](http://www.maultech.com/chrislott/resources/cstyle/)

**Comment by dschlaep** [comment]
This page is pretty awesome: "Sven Rosvall offers a style-document generator. His page lets you make some choices about various constructs, and the generator builds a HTML document for you": http://www.rosvall.ie/cgi-bin/genCodeStd.pl

I also quite like https://google.github.io/styleguide/cppguide.html except that all the c++ stuff is not relevant for `SOILWAT2`

However, I do think that it would be really helpful to find consensus on a style -- currently, we have a wild mix of styles throughout -- to which I contributed as I changed my preferences over time ...

However, I have pretty strong preferences in terms of horizontal and vertical whitespace due to eye sight problems, e.g., I have a hard time with the "GNU" and "Indented" curly braces styles (http://www.rosvall.ie/cgi-bin/genCodeStd.pl) and rather favor 2-space indentation over tabs and over 4-spaces as well as a 80-character line width limit -- so that even a large font displays the entire line of code on my screen.
